metadata_dir = "/meta"
data_dir = "/data"
db_engine = "sqlite"
replication_factor = 1
rpc_bind_addr = "0.0.0.0:3901"
rpc_secret = "1b84318922dee6eccdd2bd8be2f80b6dc8f679d61e9601659c5c49af874db068"
[s3_api]
api_bind_addr = "0.0.0.0:3900"
s3_region = "us-east-1"
