metadata_dir = "/meta"
data_dir = "/data"
db_engine = "sqlite"
replication_factor = 1
rpc_bind_addr = "0.0.0.0:3901"
rpc_secret = "fca071dbe7fa7d0e1819969abcbfaf663c1752d27df5e158ec7cdb5bb4fd9bee"
[s3_api]
api_bind_addr = "0.0.0.0:3900"
s3_region = "us-east-1"
